{
 "title": "Crypto",
 "time": { "from": "now-5y", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "target_coin",
    "label": "Focus on coin",
    "query": "from(bucket: \"primary\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r._measurement == \"crypto\"\n  )\n  |> keyValues(keyColumns: [\"coin_id\"])\n  |> group()\n  |> keep(columns: [\"coin_id\"])\n  |> distinct(column: \"coin_id\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Historical Price",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: \"primary\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crypto\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\n  |> filter(fn: (r) => contains(value: r[\"coin_id\"], set: ${target_coin:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lastest Price",
   "type": "stat",
   "gridPos": { "h": 18, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"primary\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crypto\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\n  |> filter(fn: (r) => contains(value: r[\"coin_id\"], set: ${target_coin:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Lastest Market Cap",
   "type": "stat",
   "gridPos": { "h": 18, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"primary\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crypto\")\n  |> filter(fn: (r) => r[\"_field\"] == \"market_cap\")\n  |> filter(fn: (r) => contains(value: r[\"coin_id\"], set: ${target_coin:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "24h Volume",
   "type": "stat",
   "gridPos": { "h": 18, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"primary\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crypto\")\n  |> filter(fn: (r) => r[\"_field\"] == \"volume\")\n  |> filter(fn: (r) => contains(value: r[\"coin_id\"], set: ${target_coin:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Latest Sentiment",
   "type": "gauge",
   "gridPos": { "h": 18, "w": 3, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"primary\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crypto\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sentiment\")\n  |> filter(fn: (r) => contains(value: r[\"coin_id\"], set: ${target_coin:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Historical Volume",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"primary\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crypto\")\n  |> filter(fn: (r) => r[\"_field\"] == \"volume\")\n  |> filter(fn: (r) => contains(value: r[\"coin_id\"], set: ${target_coin:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}