apiVersion: 1

deleteDatasources:
  - name: 'InfluxDB_v2'
    orgId: 1

datasources:
  - name: 'InfluxDB_v2'
    type: 'influxdb'
    access: 'proxy'
    orgId: 1
    url: 'http://influxdb:8086'
    isDefault: true
    editable: true

    jsonData:
      version: Flux
      organization: primary
      defaultBucket: primary
      tlsSkipVerify: true
      httpHeaderName1: 'Authorization'
   
    secureJsonData:
      httpHeaderValue1: 'Token deadsimple'
