version: '3'
services:

  #---------------------------------------------------------
  # Influx
  #---------------------------------------------------------
  influxdb:
    image: bitnami/influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_USER_PASSWORD=deadsimple
      - INFLUXDB_ADMIN_USER_TOKEN=deadsimple
      - INFLUXDB_USER=user1
      - INFLUXDB_USER_PASSWORD=deadsimple1
      - INFLUXDB_DB=metrics1
      - INFLUXDB_HTTP_READINESS_TIMEOUT=60
      - INFLUXDB_HTTP_AUTH_ENABLED=false

    #volumes:
    #  - /tmp/influx:/bitnami/influxdb

    networks:
      - metrics_net

  #---------------------------------------------------------
  # Grafana
  #---------------------------------------------------------
  grafana:
    image: grafana/grafana
    depends_on:
      - influxdb
    ports:
      - '3000:3000'

    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=deadsimple
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/

    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/

    networks:
      - metrics_net

  #---------------------------------------------------------
  # Grafana Renderer (for notifications)
  #---------------------------------------------------------
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - '8081:8081'

    networks:
      - metrics_net

networks:
  metrics_net:
    name: metrics_net
