{
 "title": "Container Engine Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Core User + System",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_engine_dev_cpu_system + app_engine_dev_cpu_user",
     "query": "from(bucket: \"primary\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sysinfo\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_system\" or r[\"_field\"] == \"cpu_user\" or r[\"_field\"] == \"cpu_idle\")\n  |> filter(fn: (r) => r[\"sys_id\"] == \"DockerEngine1\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r.cpu_system + r.cpu_user }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> yield(name: \"last\")\n"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(app_engine_dev_mem_avail / app_engine_dev_mem_max) * 100",
     "query": "from(bucket: \"primary\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sysinfo\")\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_max\" or r[\"_field\"] == \"mem_avail\")\n  |> filter(fn: (r) => r[\"sys_id\"] == \"DockerEngine1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r.mem_avail / r.mem_max * 100.0 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Disk Transactions/sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "TPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_engine_dev_disk_tps",
     "legendFormat": "app engine disk tps",
     "query": "from(bucket: \"primary\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sysinfo\")\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_tps\")\n  |> filter(fn: (r) => r[\"sys_id\"] == \"DockerEngine1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "min" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_engine_dev_uptime",
     "query": "from(bucket: \"primary\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sysinfo\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\n  |> filter(fn: (r) => r[\"sys_id\"] == \"DockerEngine1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(app_engine_dev_mem_avail / app_engine_dev_mem_max) * 100",
     "query": "from(bucket: \"primary\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sysinfo\")\n  |> filter(fn: (r) => r[\"_field\"] == \"df_pct\")\n  |> filter(fn: (r) => r[\"sys_id\"] == \"DockerEngine1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Egress Bandwidth/sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_engine_dev_net_out",
     "legendFormat": "app engine disk tps",
     "query": "from(bucket: \"primary\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sysinfo\")\n  |> filter(fn: (r) => r[\"_field\"] == \"net_out_rate\")\n  |> filter(fn: (r) => r[\"sys_id\"] == \"DockerEngine1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Core",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "app_engine_dev_cpu_system",
     "legendFormat": "app engine cpu system",
     "query": "from(bucket: \"primary\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sysinfo\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_system\" or r[\"_field\"] == \"cpu_idle\" or r[\"_field\"] == \"cpu_user\")\n  |> filter(fn: (r) => r[\"sys_id\"] == \"DockerEngine1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "app_engine_dev_mem_used",
     "legendFormat": "app engine memory used",
     "query": "from(bucket: \"primary\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sysinfo\")\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_avail\" or r[\"_field\"] == \"mem_used\")\n  |> filter(fn: (r) => r[\"sys_id\"] == \"DockerEngine1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "app_engine_dev_disk_rps",
     "legendFormat": "app engine read/s",
     "query": "from(bucket: \"primary\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sysinfo\")\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_rps\" or r[\"_field\"] == \"disk_wps\")\n  |> filter(fn: (r) => r[\"sys_id\"] == \"DockerEngine1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "app_engine_dev_net_in",
     "legendFormat": "app engine net in/s",
     "query": "from(bucket: \"primary\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sysinfo\")\n  |> filter(fn: (r) => r[\"_field\"] == \"net_out_rate\" or r[\"_field\"] == \"net_in_rate\")\n  |> filter(fn: (r) => r[\"sys_id\"] == \"DockerEngine1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}